CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name                VARCHAR(250) NOT NULL,
  email               VARCHAR(254) NOT NULL,
  comments_banned_until           TIMESTAMP,
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
  CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name                VARCHAR(255) NOT NULL,
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name),
  CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title               VARCHAR(120) NOT NULL,
  annotation          VARCHAR(2000) NOT NULL,
  description         VARCHAR(7000) NOT NULL,
  category_id         BIGINT NOT NULL,
  initiator_id        BIGINT NOT NULL,
  event_date          TIMESTAMP NOT NULL,
  lat                 FLOAT NOT NULL,
  lon                 FLOAT NOT NULL,
  paid                BOOLEAN NOT NULL,
  participant_limit   INTEGER NOT NULL,
  request_moderation  BOOLEAN NOT NULL,
  state               VARCHAR(50) NOT NULL,
  created_on          TIMESTAMP NOT NULL,
  published_on        TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES categories(id),
  FOREIGN KEY (initiator_id) REFERENCES users(id),
  CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_id            BIGINT NOT NULL,
  requester_id        BIGINT NOT NULL,
  status              VARCHAR(50) NOT NULL,
  created             TIMESTAMP NOT NULL,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT UQ_PARTICIPANT_PER_EVENT UNIQUE (event_id, requester_id),
  CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title               VARCHAR(255) NOT NULL,
  pinned              BOOLEAN NOT NULL,
  CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
  event_id            BIGINT NOT NULL,
  compilation_id      BIGINT NOT NULL,
  PRIMARY KEY (event_id, compilation_id),
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text                VARCHAR(2000) NOT NULL,
  author_id           BIGINT NOT NULL,
  event_id            BIGINT NOT NULL,
  published_on        TIMESTAMP NOT NULL,
  updated_on          TIMESTAMP,
  status              VARCHAR(50) NOT NULL,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
)